// generated by cad/make_variant.py from the simulated 'gojira' design - do not edit
include <suit_tail.scad>
joint_count = 10;
tail_length = 1800.0;
mech_length = 1500.0;
root_diameter = 190.0;
last_mech_diameter = 70.0;
tip_diameter = 35.0;
taper_exponent = 1.3;
skin_root = 20.0;
skin_tip = 4.0;
cord_preload = 10.0;
pitch_ratio = 0.7;
max_roll = 7.0;
root_pitch = 55.01404279706373;
max_yaw = [8.0, 9.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 23.0, 26.0];
max_pitch = [for (y = max_yaw) y * pitch_ratio];
rest_droop_list = [0.0, -2.4323, -2.9178, -3.5571, -4.4087, -5.5435, -7.0191, -8.7917, -10.5453, -11.6136];
