// generated by cad/make_variant.py from the simulated 'barney' design - do not edit
include <suit_tail.scad>
joint_count = 6;
tail_length = 900.0;
mech_length = 750.0;
root_diameter = 190.0;
last_mech_diameter = 100.0;
tip_diameter = 60.0;
taper_exponent = 1.0;
skin_root = 20.0;
skin_tip = 10.0;
cord_preload = 10.0;
pitch_ratio = 1.0;
max_roll = 7.0;
root_pitch = 11.160052952828897;
root_dz = -30.0;
plate_z = 40.0;
ball_ratio = 0.15;
ball_min = 20.0;
ball_max = 28.0;
max_yaw = [8.0, 11.0, 14.0, 18.0, 22.0, 26.0];
max_pitch = [for (y = max_yaw) y * pitch_ratio];
rest_droop_list = [0.0, 19.8994, 19.4052, 8.8064, -5.9454, -17.9095];
