"""Parametric FreeCAD model of the passive suit tail (README section 19).

Run headless from WSL:

    ~/Applications/freecad-experiment/squashfs-root/usr/bin/freecadcmd cad/freecad/build_tail.py

Every vertebra is generated by createVertebra(index, parameters) from the
shared dimensional spec cad/geometry.py (the same formulas as the OpenSCAD
model and the physics model). Outputs in cad/freecad/output/:
  suit_tail.FCStd, suit_tail.step, test_section_4joint.step, build_report.json
"""
import json
import math
import os
import sys
import traceback
from pathlib import Path

HERE = Path(os.environ.get("TAIL_CAD_DIR", Path(__file__).resolve().parent if "__file__" in globals() else "."))
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT))

import FreeCAD as App  # noqa: E402
import Part  # noqa: E402

from cad import geometry as g  # noqa: E402

V = App.Vector
OUT = HERE / "output"
OUT.mkdir(exist_ok=True)
X, Y, Z = V(1, 0, 0), V(0, 1, 0), V(0, 0, 1)
FUZZ = 0.0           # mm; >0 enables fuzzy booleans (made the caps invalid in FreeCAD 1.1)

# ----------------------------------------------------------------- primitives


def cyl_x(r, x0, x1):
    """Cylinder along X from x0 to x1."""
    lo, hi = min(x0, x1), max(x0, x1)
    return Part.makeCylinder(r, hi - lo, V(lo, 0, 0), X)


def cone_x(r0, r1, x0, x1):
    """Cone along X with radius r0 at x0 and r1 at x1."""
    if x1 >= x0:
        return Part.makeCone(r0, r1, x1 - x0, V(x0, 0, 0), X)
    return Part.makeCone(r1, r0, x0 - x1, V(x1, 0, 0), X)


def rot_x(shape, deg):
    s = shape.copy()
    s.rotate(V(0, 0, 0), X, deg)
    return s


def at_lobes(make):
    return [rot_x(make(), a) for a in (45, 135, 225, 315)]


def at_springs(make):
    # +Z (dorsal), -Y and +Y (lateral)
    return [rot_x(make(), a) for a in (0, 90, -90)]


def fuse(shapes):
    """Multi-argument boolean union (sequential fuses can fail in OCC on coplanar faces)."""
    s = shapes[0].multiFuse(shapes[1:], FUZZ) if len(shapes) > 1 else shapes[0]
    s = s.removeSplitter()
    if not s.isValid():
        s.fix(1e-4, 1e-4, 1e-3)
    if s.Volume <= 0:
        raise RuntimeError("fuse produced an empty shape")
    return s


def cut(base, tools):
    v0 = base.Volume
    out = base.cut(tools, FUZZ) if tools else base
    if out.Volume <= 0.2 * v0:
        # fall back to sequential cuts if the multi-tool cut misbehaves
        out = base
        for t in tools:
            out = out.cut(t)
    if out.Volume <= 0:
        raise RuntimeError("cut produced an empty shape")
    return out


def hex_prism_x(af, x0, length, zoff):
    r = af / math.sqrt(3) + 0.2
    pts = [V(x0, r * math.cos(math.radians(60 * k + 30)), zoff + r * math.sin(math.radians(60 * k + 30))) for k in range(7)]
    face = Part.Face(Part.makePolygon(pts))
    return face.extrude(V(length, 0, 0))


def ellip_cone_mx(h, by, bp):
    """Cone with apex at the origin opening toward -X; half-angles by (Y) and bp (Z)."""
    c = Part.makeCone(0, h, h, V(0, 0, 0), V(-1, 0, 0))
    m = App.Matrix()
    m.scale(1, math.tan(math.radians(by)), math.tan(math.radians(bp)))
    return c.transformGeometry(m)


def hull_solid(pts):
    """Convex hull of points as a solid (the OpenSCAD hull() equivalent)."""
    import numpy as np
    from scipy.spatial import ConvexHull
    a = np.array([[q.x, q.y, q.z] for q in pts])
    h = ConvexHull(a)
    faces = []
    for simplex, eq in zip(h.simplices, h.equations):
        t = [a[k] for k in simplex]
        if np.dot(np.cross(t[1] - t[0], t[2] - t[0]), eq[:3]) < 0:
            t = [t[0], t[2], t[1]]
        v = [V(*q) for q in t]
        faces.append(Part.Face(Part.makePolygon(v + [v[0]])))
    sol = Part.Solid(Part.Shell(faces)).removeSplitter()
    if sol.Volume < 0:
        sol.reverse()
    return sol


def box_pts(x0, x1, y0, y1, z0, z1):
    return [V(x, y, z) for x in (x0, x1) for y in (y0, y1) for z in (z0, z1)]


def circle_pts_x(r, x, c=(0.0, 0.0), n=72):
    """Points of a circle of radius r in the plane x = const, centred at (y, z) = c."""
    return [V(x, c[0] + r * math.cos(2 * math.pi * k / n), c[1] + r * math.sin(2 * math.pi * k / n)) for k in range(n)]


def prism_x_yz(poly_yz, x0, length):
    """Prism along X from a polygon given in the (y, z) plane."""
    v = [V(x0, y, z) for y, z in poly_yz]
    return Part.Face(Part.makePolygon(v + [v[0]])).extrude(V(length, 0, 0))


def prism_z_xy(poly_xy, z0, length):
    """Prism along Z from a polygon given in the (x, y) plane."""
    v = [V(x, y, z0) for x, y in poly_xy]
    return Part.Face(Part.makePolygon(v + [v[0]])).extrude(V(0, 0, length))


# ------------------------------------------------------------------- parts


def createBall(i, p):
    R, rn, df, ft = g.RB(p, i), g.RN(p, i), g.DF(p, i), g.flange_t(p)
    pin = g.pin_spec(p, i)
    d = g.droop(p, i)
    x1 = g.cap_h(p, i) + 3            # neck stays on the joint axis through the cap mouth

    def par(s):                       # into the parent-axis frame (wedge flange)
        s = s.copy()
        s.rotate(V(0, 0, 0), Y, -d)
        return s
    parts = [Part.makeSphere(R), cyl_x(rn, -x1, 0), par(cyl_x(g.flange_r(p, i), -df - ft, -df)), par(cyl_x(rn, -df, -x1))]
    if abs(d) > 0.01:
        parts += [Part.makeSphere(rn, V(-x1, 0, 0)), par(Part.makeSphere(rn, V(-x1, 0, 0)))]
    body = fuse(parts)
    tools = [cyl_x(g.bore_r(p), -x1 - 1, 0.1), par(cyl_x(g.bore_r(p), -df - ft - 1, 0.1)),
             cone_x(g.bore_r(p), g.bore_r(p) + (R + 1) * math.tan(math.radians(g.cord_flare(p, i))), 0, R + 1)]
    fb = g.flange_bolt_r(p, i)
    tools += [par(t) for t in at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, ft + 2, V(-df - ft - 1, 0, fb), X))]
    zp = g.pin_pocket_z(p, i)
    tools.append(Part.makeCylinder(pin[2] / 2 + 0.3, pin[3] + 0.2, V(0, 0, zp - pin[3]), Z))
    tools.append(Part.makeCylinder(pin[0] / 2 + 0.15, R + 1, V(0, 0, zp), Z))
    return cut(body, tools)


def socket_cavity(i, p):
    Rs = g.RS(p, i)
    s45 = math.sin(math.radians(45))
    return Part.makeSphere(Rs).fuse(cone_x(Rs * s45, 0.01, -Rs * s45, -Rs * math.sqrt(2)))


def roll_slot(i, p, x_lo, x_hi):
    pin = g.pin_spec(p, i)
    w = g.slot_width(p, i)
    r0, r1 = g.RS(p, i) - 0.5, g.RB(p, i) + p.pin_protrude + 1.0
    shell = Part.makeSphere(r1).cut(Part.makeSphere(r0 - 0.01))
    slab = Part.makeBox(x_hi - x_lo, w, r1 + 1, V(x_lo, -w / 2, 0))
    a = g.pitch_lim(p, i) + math.degrees(math.asin((pin[0] / 2 + 0.5) / g.RB(p, i))) + 2
    h1 = Part.makeBox(400, 400, 400, V(-400, -200, -200)); h1.rotate(V(0, 0, 0), Y, a)
    h2 = Part.makeBox(400, 400, 400, V(0, -200, -200)); h2.rotate(V(0, 0, 0), Y, -a)
    return shell.common(slab).common(h1.common(h2))


def createCap(i, p):
    h, ro, pcd, lr, t = g.cap_h(p, i), g.cap_outer_r(p, i), g.bolt_pcd_r(p, i), g.lobe_r(p), g.cap_lobe_t(p)
    lobes = at_lobes(lambda: Part.makeCylinder(lr, t, V(-t, 0, pcd), X).fuse(Part.makeBox(t, 2 * lr, pcd - ro + 3, V(-t, -lr, ro - 3))))
    w, et, ex = g.spring_arm(p, i), g.cap_ear_t(p, i), p.cap_ear_x
    ew = g.ear_w(p, i)
    ears = at_springs(lambda: Part.makeBox(et, ew, w - ro + 4 + ex, V(-et, -ew / 2, ro - 4)))
    body = fuse([cyl_x(ro, -h, 0)] + lobes + ears)
    tools = [socket_cavity(i, p), ellip_cone_mx(h + 2, g.beta_y(p, i), g.beta_p(p, i)), roll_slot(i, p, -h - 1, 0.01)]
    tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, t + 2, V(-t - 1, 0, pcd), X))
    tools += at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 40, V(-ex, 20, w), V(0, -1, 0)))
    return cut(body, tools)


def fin_windows(i, p):
    bl, rf = g.body_len(p, i), g.RF(p, i)
    x_f0 = 0.0
    xm = x_f0 + 0.5 * (bl - x_f0)
    out = []
    for s0, s1 in ((x_f0 + 7, xm - 2), (xm + 2 * p.line_w + 10, bl - g.flange_t(p) - 3)):
        r_in = (g.cap_outer_r(p, i) if s0 < g.seat_depth(p, i) + 3 else spine_r(i, p)) + 4
        r_out = rf - 7
        h = min((s1 - s0) / 2 - 1, (r_out - r_in) / 2)
        if h <= 5:
            continue
        nr = max(1, int((r_out - r_in + 3) // (2 * h + 3)))
        for k in range(nr):
            b = Part.makeBox(h * math.sqrt(2), 20, h * math.sqrt(2), V(-h / math.sqrt(2), -10, -h / math.sqrt(2)))
            b.rotate(V(0, 0, 0), Y, 45)
            b.translate(V((s0 + s1) / 2, 0, r_in + h + k * (2 * h + 3)))
            out.append(b)
    return out


def spine_r(i, p):
    if i < p.joint_count:
        return max(g.flange_bolt_r(p, i + 1) - 5.3, g.bore_r(p) + g.wall(p))
    return g.bore_r(p) + g.wall(p, 4)


def skin_ring_skirt(i, p):
    """Single-line wall from the bed (distal end) up to the skin ring's bottom rim, 45 deg flare to the rim's full
    width, pointed arches open from the bed between the fins, notches at the spring anchors (as suit_tail.scad)."""
    bl, rf, n = g.body_len(p, i), g.RF(p, i), p.joint_count
    skirt_t = p.line_w + 0.1
    x0 = 0.5 * bl + 2 * p.line_w + 0.2 + 8
    r_o = rf - 8
    r_i = r_o - skirt_t
    rim_w = 3 * p.line_w
    flare = rim_w - skirt_t
    h = bl - x0
    band = flare + 2
    arc = 2 * math.pi * r_o / 4 - g.fin_t(p, i) - 12
    na = max(1, math.ceil(arc / 45))
    W = min((arc - (na - 1) * 4) / na, 2 * (h - band))
    hv = h - band - W / 2
    shell = cyl_x(r_o, x0 - 0.01, bl).cut(cyl_x(r_i, x0 - 1, bl + 1))
    fl = cyl_x(r_o, x0 - 0.01, x0 + flare).cut(cone_x(r_o - rim_w, r_i, x0 - 0.02, x0 + flare + 0.01))
    wall = fuse([shell, fl])
    tools = []
    if hv >= 0:
        arch = [(bl + 1, -W / 2), (bl - hv, -W / 2), (bl - hv - W / 2, 0), (bl - hv, W / 2), (bl + 1, W / 2)]
        for q in range(4):
            for k in range(na):
                tools.append(rot_x(prism_z_xy(arch, r_o - 10, 20), q * 90 + (k + 0.5) * 90 / na))
    if i < n:
        notch = [(bl + 1, -7), (bl - 11, -7), (bl - 18, 0), (bl - 11, 7), (bl + 1, 7)]
        tools += at_springs(lambda: prism_z_xy(notch, r_o - 10, 20))
    return cut(wall, tools)


def createFrame(i, p):
    bl, sd, rf, ho = g.body_len(p, i), g.seat_depth(p, i), g.RF(p, i), g.cap_outer_r(p, i)
    pcd, lr, n = g.bolt_pcd_r(p, i), g.lobe_r(p), p.joint_count
    fin_t = g.fin_t(p, i)
    x_f0 = 0.0
    rr = g.flange_r(p, i + 1) if i < n else spine_r(i, p) + 6
    parts = [cyl_x(ho, 0, sd), cyl_x(spine_r(i, p), sd - 2, bl), cyl_x(rr, bl - g.flange_t(p), bl)]
    # cap-bolt lobes with 45 deg undersides
    drop = pcd + lr - ho + 3
    parts += at_lobes(lambda: Part.makeCylinder(lr, 7, V(0, 0, pcd), X).fuse(
        Part.makeLoft([Part.Wire(Part.makeCircle(lr, V(7, 0, pcd), X)), Part.Wire(Part.makeCircle(1, V(7 + drop, 0, ho - 3), X))], True)))
    # fins, with the diamond windows cut from the fins only (so they never notch the housing cone)
    fins = fuse([rot_x(Part.makeBox(bl - x_f0, fin_t, rf, V(x_f0, -fin_t / 2, 0)), a) for a in (0, 90, 180, 270)])
    parts.append(cut(fins, [rot_x(w, a) for a in (0, 90, 180, 270) for w in fin_windows(i, p)]))
    # 45 deg cone under the socket housing, down to the spine (no flat ceiling between the fins)
    parts.append(cone_x(ho, spine_r(i, p), sd - 0.01, sd + ho - spine_r(i, p)))
    parts.append(skin_ring_skirt(i, p))
    xm = x_f0 + 0.5 * (bl - x_f0)
    t = 2 * p.line_w + 0.2
    ring = cyl_x(rf, xm, xm + t).cut(cyl_x(rf - 3 * p.line_w, xm - 1, xm + t + 1))
    skirt = cone_x(rf, rf - 8, xm + t, xm + t + 8).cut(cone_x(rf - 3 * p.line_w, rf - 8 - 3 * p.line_w, xm + t - 0.01, xm + t + 8.01))
    base = cyl_x(rf, bl - g.flange_t(p), bl).cut(cyl_x(rf - 3 * p.line_w, bl - g.flange_t(p) - 1, bl + 1))
    if i < n:
        w2 = g.spring_arm(p, i + 1)
        ft = g.fin_t(p, i)
        parts += at_springs(lambda: Part.makeCylinder(7, ft + 4, V(bl - 4, (ft + 4) / 2, w2), V(0, -1, 0)).common(
            Part.makeBox(20, 40, 400, V(bl - 20, -20, 0))))
    body = fuse(parts + [ring, skirt, base])
    tools = [socket_cavity(i, p), roll_slot(i, p, -0.01, sd), cyl_x(g.bore_r(p), -1, bl + 1)]
    tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, 12, V(-1, 0, pcd), X).fuse(hex_prism_x(p.nut_af, 7 - p.nut_h - 0.3, 20, pcd)))
    if i < n:
        w2 = g.spring_arm(p, i + 1)
        tools += at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 20, V(bl - 4, 10, w2), V(0, -1, 0)))
        fb = g.flange_bolt_r(p, i + 1)
        tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, g.flange_t(p) + 2, V(bl - g.flange_t(p) - 1, 0, fb), X).fuse(
            hex_prism_x(p.nut_af, bl - g.flange_t(p) + 2.5 - 20, 20, fb)))
    else:
        tools += at_lobes(lambda: Part.makeCylinder(1.6, g.flange_t(p) + 2, V(bl - g.flange_t(p) - 1, 0, spine_r(i, p) + 2), X))
    return cut(body, tools)


def createTipAdapter(p):
    n = p.joint_count
    r = spine_r(n, p) + 6
    L = g.tip_plug_len(p)
    body = fuse([cyl_x(r, 0, 6), cyl_x(10.5, 0, L), cone_x(7, 2, L, L + 45)] +
                [cone_x(8 - 1.2 * k, 5 - 1.2 * k, L + 8 + 9 * k, L + 13 + 9 * k) for k in range(4)])
    tools = [cyl_x(g.bore_r(p), -1, 7), cyl_x(7, 6, L - 3), Part.makeBox(L - 13, 12, 10, V(8, 0, -5))]
    tools += at_lobes(lambda: Part.makeCylinder(1.6, 8, V(-1, 0, spine_r(n, p) + 2), X))
    return cut(body, tools)


def root_placement(p):
    th = math.radians(p.root_pitch)
    ex, ez = V(-math.cos(th), 0, -math.sin(th)), V(-math.sin(th), 0, math.cos(th))
    ey = ez.cross(ex)
    m = App.Matrix(ex.x, ey.x, ez.x, -p.root_back_offset,
                   ex.y, ey.y, ez.y, 0,
                   ex.z, ey.z, ez.z, 0,
                   0, 0, 0, 1)
    pl = App.Placement(m)
    pl.Base = V(-p.root_back_offset, 0, p.root_dz)
    return pl


KNOT_R, KNOT_DEPTH = 11.0, 10.0    # cord knot pocket in the plate's front face
HOLE_R = 12.7                      # plate lightening hexes: 22 mm across flats
HOLE_PITCH = 28.0                  # honeycomb pitch: 6 mm web between every pair of neighbours
HOLE_Y0, HOLE_Z0 = HOLE_PITCH / 2, -5.5   # grid phase that fits the most holes (17) symmetrically


def hip_holes(p):
    """Hex lightening-hole centres (y, z) on the harness plate, same rule as suit_tail.scad hip_hole_ok()."""
    m, bz, lz, w = 6 + HOLE_R, p.root_dz, p.root_dz + 6, g.spring_arm(p, 1)
    fin_t = 3 * p.line_w + 0.1
    out = []
    for r in range(-8, 9):
        for c in range(-8, 9):
            y = (c + (0 if r % 2 == 0 else 0.5)) * HOLE_PITCH + HOLE_Y0
            z = p.plate_z + r * HOLE_PITCH * math.sin(math.radians(60)) + HOLE_Z0
            ok = (abs(y) <= p.hip_plate_w / 2 - 8 - HOLE_R and abs(z - p.plate_z) <= p.hip_plate_h / 2 - 8 - HOLE_R
                  and math.hypot(y, z - bz) >= g.flange_r(p, 1) + 6 + m
                  and not (abs(y) < fin_t / 2 + m and bz < z < bz + w + 5 + m)
                  and not (abs(z - lz) < fin_t / 2 + 4 + m and abs(y) < w + 5 + m)
                  and not (abs(abs(y) - 78) < 2.5 + m and (abs(z - (p.plate_z - 45)) < 14 + m or abs(z - (p.plate_z + 45)) < 14 + m))
                  and not (abs(y) < 26 + m and abs(z - (p.plate_z + p.hip_plate_h / 2 - 10)) < 2.5 + m))
            if ok:
                out.append((y, z))
    return out


def createHipMount(p):
    """Harness plate + boss + spring anchor arms with webs, built in the pelvis frame (mirrors suit_tail.scad)."""
    P = root_placement(p)
    pf = g.DF(p, 1) + g.flange_t(p)
    w = g.spring_arm(p, 1)
    fin_t = 3 * p.line_w + 0.1
    arm_t = 12.0                      # dorsal spring up to ~220 N: 12 mm thick, 30 mm deep at the boss
    pb = -p.harness_plate_offset - p.hip_plate_t

    def to_pelvis(pts, a=0.0):
        R = App.Rotation(X, a)
        return [P.multVec(R.multVec(q)) for q in pts]

    def arm_pts(t, dx=0.0):
        return (box_pts(-pf - 12 + dx, -pf + dx, -t / 2, t / 2, 0, w + 5) +
                box_pts(-pf - 30 + dx, -pf + dx, -t / 2, t / 2, 0, 12))

    plate = Part.makeBox(p.hip_plate_t, p.hip_plate_w, p.hip_plate_h, V(pb, -p.hip_plate_w / 2, p.plate_z - p.hip_plate_h / 2))
    # boss: hull from a disc on the plate's FRONT face (so it stands on the print bed) to the ball-1 flange
    fr = g.flange_r(p, 1)
    boss = hull_solid([q for x in (-p.harness_plate_offset - 1, -p.harness_plate_offset)
                       for q in circle_pts_x(fr + 6, x, (0.0, p.root_dz))] +
                      to_pelvis(circle_pts_x(fr, -pf) + circle_pts_x(fr, -pf - 8)))
    solids = [plate, boss]
    for a in (0, 90, -90):
        arm = to_pelvis(arm_pts(arm_t), a)
        thin = to_pelvis(arm_pts(fin_t), a)
        solids.append(hull_solid(arm))
        solids.append(hull_solid(arm + to_pelvis(arm_pts(fin_t, -(arm_t - fin_t) / 2), a)))          # 45 deg flare
        solids.append(hull_solid(thin + [V(pb + 1 + 0.001 * (q.x - pb), q.y, q.z) for q in thin]))   # web to the plate
    body = fuse(solids)

    def place(s):
        return s.transformGeometry(P.toMatrix())

    behind = Part.makeBox(1000, 1000, 1000, V(pb - 1000, -500, -500))
    tools = [place(Part.makeBox(100, 200, 200, V(-pf + 0.01, -100, -100))).common(behind)]
    tools.append(place(cyl_x(g.bore_r(p), -pf - 120, 0)))
    kz = p.root_dz + (p.root_back_offset - p.harness_plate_offset) * math.tan(math.radians(p.root_pitch))
    # knot pocket: 22 mm x 10 mm deep from the front face, then a 45 deg roof down to the bore
    kx = -p.harness_plate_offset + 0.01
    tools.append(Part.makeCylinder(KNOT_R, KNOT_DEPTH + 0.01, V(kx, 0, kz), V(-1, 0, 0)))
    tools.append(Part.makeCone(KNOT_R, 0, KNOT_R, V(kx - KNOT_DEPTH, 0, kz), V(-1, 0, 0)))   # to a point: the tilted bore pierces it
    tools += [place(s) for s in at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, 12, V(-pf - 11, 0, g.flange_bolt_r(p, 1)), X).fuse(
        hex_prism_x(p.nut_af, -pf - 26, 20, g.flange_bolt_r(p, 1))))]
    tools += [place(s) for s in at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 20, V(-g.spring_span_parent(p, 1), 10, w), V(0, -1, 0)))]
    for y in (-78, 78):
        for zz in (-45, 45):
            tools.append(Part.makeBox(p.hip_plate_t + 2, 5, 28, V(pb - 1, y - 2.5, p.plate_z + zz - 14)))
    tools.append(Part.makeBox(p.hip_plate_t + 2, 52, 5, V(pb - 1, -26, p.plate_z + p.hip_plate_h / 2 - 10 - 2.5)))
    hexagon = [(HOLE_R * math.cos(math.radians(30 + 60 * k)), HOLE_R * math.sin(math.radians(30 + 60 * k))) for k in range(6)]   # flats face the neighbours
    for y, z in hip_holes(p):
        tools.append(prism_x_yz([(y + a, z + b) for a, b in hexagon], pb - 1, p.hip_plate_t + 2))
    return cut(body, tools)


# ------------------------------------------------------------------ document


def add(doc, group, name, shape, placement, color):
    o = doc.addObject("Part::Feature", name)
    o.Shape = shape
    o.Placement = placement
    if hasattr(o, "ViewObject") and o.ViewObject is not None:
        o.ViewObject.ShapeColor = color
    group.addObject(o)
    return o


def createVertebra(index, parameters, doc, parent, placement):
    """Vertebra `index` = its socket (seat is part of the frame, plus the bolted
    cap), its frame, and the ball of the next joint bolted to its distal flange."""
    p = parameters
    grp = doc.addObject("App::DocumentObjectGroup", f"Vertebra{index:02d}")
    parent.addObject(grp)
    add(doc, grp, f"Vertebra{index:02d}_Frame", createFrame(index, p), placement, (0.26, 0.45, 0.70))
    add(doc, grp, f"Vertebra{index:02d}_Socket", createCap(index, p), placement, (0.70, 0.78, 0.90))
    L = g.spacing(p)
    if index < p.joint_count:
        add(doc, grp, f"Vertebra{index:02d}_Ball", createBall(index + 1, p),
            placement.multiply(App.Placement(V(L, 0, 0), App.Rotation(Y, g.droop(p, index + 1)))), (0.85, 0.65, 0.13))
    else:
        add(doc, grp, f"Vertebra{index:02d}_TipAdapter", createTipAdapter(p),
            placement.multiply(App.Placement(V(g.body_len(p, index), 0, 0), App.Rotation())), (0.85, 0.65, 0.13))
    return grp


def build(p, joints=None, name="SuitTail"):
    doc = App.newDocument(name)
    top = doc.addObject("App::DocumentObjectGroup", name)
    sheet = doc.addObject("Spreadsheet::Sheet", "Parameters")
    for k, (key, val) in enumerate(json.loads(p.to_json()).items()):
        sheet.set(f"A{k+1}", key)
        sheet.set(f"B{k+1}", str(val) if isinstance(val, list) else f"{val}")
    hip = doc.addObject("App::DocumentObjectGroup", "HipMount")
    top.addObject(hip)
    add(doc, hip, "HipMount_Plate", createHipMount(p), App.Placement(), (0.3, 0.3, 0.3))
    P = root_placement(p)
    add(doc, hip, "HipMount_Ball", createBall(1, p), P, (0.85, 0.65, 0.13))
    L = g.spacing(p)
    joints = joints or p.joint_count
    pts = [P.multVec(V(-g.DF(p, 1) - 20, 0, 0))]
    pl = P
    for i in range(1, joints + 1):
        if i > 1:
            pl = pl.multiply(App.Placement(V(L, 0, 0), App.Rotation(Y, g.droop(p, i))))
        createVertebra(i, p, doc, top, pl)
        pts.append(pl.Base)
    end = pl.multVec(V(L, 0, 0))
    pts.append(end)
    cord = doc.addObject("Part::Feature", "CentralCord")
    cord.Shape = Part.makePolygon(pts)
    top.addObject(cord)
    if joints == p.joint_count:
        tip = doc.addObject("Part::Feature", "FoamTipReference")
        tl = p.tail_length - p.mech_length
        tip.Shape = cone_x(p.last_mech_diameter / 2, p.tip_diameter / 2, 0, tl)
        tip.Placement = pl.multiply(App.Placement(V(L, 0, 0), App.Rotation()))
        top.addObject(tip)
    doc.recompute()
    return doc


VARIANT = os.environ.get("TAIL_VARIANT", "")


def load_params():
    if VARIANT:
        return g.CadParams(**json.loads((ROOT / "cad" / "variants" / f"{VARIANT}.json").read_text()))
    return g.CadParams()


def main():
    p = load_params()
    sfx = f"_{VARIANT}" if VARIANT else ""
    report = {"checks_failed": [c for c in g.checks(p) if not c[1]]}
    doc = build(p)
    shapes = [o for o in doc.Objects if o.TypeId == "Part::Feature" and o.Name != "CentralCord"]
    for o in shapes:
        report.setdefault("valid", {})[o.Name] = bool(o.Shape.isValid())
        report.setdefault("volume_cm3", {})[o.Name] = round(o.Shape.Volume / 1000, 2)
    Part.export(shapes, str(OUT / f"suit_tail{sfx}.step"))
    doc.saveAs(str(OUT / f"suit_tail{sfx}.FCStd"))
    App.closeDocument(doc.Name)
    doc4 = build(p, joints=4, name="TestSection4")
    Part.export([o for o in doc4.Objects if o.TypeId == "Part::Feature" and o.Name != "CentralCord"], str(OUT / f"test_section_4joint{sfx}.step"))
    doc4.saveAs(str(OUT / f"test_section_4joint{sfx}.FCStd"))
    (OUT / f"build_report{sfx}.json").write_text(json.dumps(report, indent=1))
    print("BUILD_OK", sum(report["valid"].values()), "/", len(report["valid"]), "valid solids")


try:
    main()
except Exception:
    traceback.print_exc()
    (OUT / "build_report.json").write_text(json.dumps({"error": traceback.format_exc()}))
    raise
