"""Parametric FreeCAD model of the passive suit tail (README section 19).

Run headless from WSL:

    ~/Applications/freecad-experiment/squashfs-root/usr/bin/freecadcmd cad/freecad/build_tail.py

Every vertebra is generated by createVertebra(index, parameters) from the
shared dimensional spec cad/geometry.py (the same formulas as the OpenSCAD
model and the physics model). Outputs in cad/freecad/output/:
  suit_tail.FCStd, suit_tail.step, test_section_4joint.step, build_report.json
"""
import json
import math
import os
import sys
import traceback
from pathlib import Path

HERE = Path(os.environ.get("TAIL_CAD_DIR", Path(__file__).resolve().parent if "__file__" in globals() else "."))
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT))

import FreeCAD as App  # noqa: E402
import Part  # noqa: E402

from cad import geometry as g  # noqa: E402

V = App.Vector
OUT = HERE / "output"
OUT.mkdir(exist_ok=True)
X, Y, Z = V(1, 0, 0), V(0, 1, 0), V(0, 0, 1)
FUZZ = 0.0           # mm; >0 enables fuzzy booleans (made the caps invalid in FreeCAD 1.1)

# ----------------------------------------------------------------- primitives


def cyl_x(r, x0, x1):
    """Cylinder along X from x0 to x1."""
    lo, hi = min(x0, x1), max(x0, x1)
    return Part.makeCylinder(r, hi - lo, V(lo, 0, 0), X)


def cone_x(r0, r1, x0, x1):
    """Cone along X with radius r0 at x0 and r1 at x1."""
    if x1 >= x0:
        return Part.makeCone(r0, r1, x1 - x0, V(x0, 0, 0), X)
    return Part.makeCone(r1, r0, x0 - x1, V(x1, 0, 0), X)


def rot_x(shape, deg):
    s = shape.copy()
    s.rotate(V(0, 0, 0), X, deg)
    return s


def at_lobes(make):
    return [rot_x(make(), a) for a in (45, 135, 225, 315)]


def at_springs(make):
    # +Z (dorsal), -Y and +Y (lateral)
    return [rot_x(make(), a) for a in (0, 90, -90)]


def fuse(shapes):
    """Multi-argument boolean union (sequential fuses can fail in OCC on coplanar faces)."""
    s = shapes[0].multiFuse(shapes[1:], FUZZ) if len(shapes) > 1 else shapes[0]
    s = s.removeSplitter()
    if not s.isValid():
        s.fix(1e-4, 1e-4, 1e-3)
    if s.Volume <= 0:
        raise RuntimeError("fuse produced an empty shape")
    return s


def cut(base, tools):
    v0 = base.Volume
    out = base.cut(tools, FUZZ) if tools else base
    if out.Volume <= 0.2 * v0:
        # fall back to sequential cuts if the multi-tool cut misbehaves
        out = base
        for t in tools:
            out = out.cut(t)
    if out.Volume <= 0:
        raise RuntimeError("cut produced an empty shape")
    return out


def hex_prism_x(af, x0, length, zoff):
    r = af / math.sqrt(3) + 0.2
    pts = [V(x0, r * math.cos(math.radians(60 * k + 30)), zoff + r * math.sin(math.radians(60 * k + 30))) for k in range(7)]
    face = Part.Face(Part.makePolygon(pts))
    return face.extrude(V(length, 0, 0))


def ellip_cone_mx(h, by, bp):
    """Cone with apex at the origin opening toward -X; half-angles by (Y) and bp (Z)."""
    c = Part.makeCone(0, h, h, V(0, 0, 0), V(-1, 0, 0))
    m = App.Matrix()
    m.scale(1, math.tan(math.radians(by)), math.tan(math.radians(bp)))
    return c.transformGeometry(m)


# ------------------------------------------------------------------- parts


def createBall(i, p):
    R, rn, df, ft = g.RB(p, i), g.RN(p, i), g.DF(p, i), g.flange_t(p)
    pin = g.pin_spec(p, i)
    body = fuse([Part.makeSphere(R), cyl_x(rn, -df, 0), cyl_x(g.flange_r(p, i), -df - ft, -df)])
    tools = [cyl_x(g.bore_r(p), -df - ft - 1, 0.1),
             cone_x(g.bore_r(p), g.bore_r(p) + (R + 1) * math.tan(math.radians(g.cord_flare(p, i))), 0, R + 1)]
    fb = g.flange_bolt_r(p, i)
    tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, ft + 2, V(-df - ft - 1, 0, fb), X))
    zp = g.pin_pocket_z(p, i)
    tools.append(Part.makeCylinder(pin[2] / 2 + 0.3, pin[3] + 0.2, V(0, 0, zp - pin[3]), Z))
    tools.append(Part.makeCylinder(pin[0] / 2 + 0.15, R + 1, V(0, 0, zp), Z))
    return cut(body, tools)


def socket_cavity(i, p):
    Rs = g.RS(p, i)
    s45 = math.sin(math.radians(45))
    return Part.makeSphere(Rs).fuse(cone_x(Rs * s45, 0.01, -Rs * s45, -Rs * math.sqrt(2)))


def roll_slot(i, p, x_lo, x_hi):
    pin = g.pin_spec(p, i)
    w = g.slot_width(p, i)
    r0, r1 = g.RS(p, i) - 0.5, g.RB(p, i) + p.pin_protrude + 1.0
    shell = Part.makeSphere(r1).cut(Part.makeSphere(r0 - 0.01))
    slab = Part.makeBox(x_hi - x_lo, w, r1 + 1, V(x_lo, -w / 2, 0))
    a = g.pitch_lim(p, i) + math.degrees(math.asin((pin[0] / 2 + 0.5) / g.RB(p, i))) + 2
    h1 = Part.makeBox(400, 400, 400, V(-400, -200, -200)); h1.rotate(V(0, 0, 0), Y, a)
    h2 = Part.makeBox(400, 400, 400, V(0, -200, -200)); h2.rotate(V(0, 0, 0), Y, -a)
    return shell.common(slab).common(h1.common(h2))


def createCap(i, p):
    h, ro, pcd, lr, t = g.cap_h(p, i), g.cap_outer_r(p, i), g.bolt_pcd_r(p, i), g.lobe_r(p), g.cap_lobe_t(p)
    lobes = at_lobes(lambda: Part.makeCylinder(lr, t, V(-t, 0, pcd), X).fuse(Part.makeBox(t, 2 * lr, pcd - ro + 3, V(-t, -lr, ro - 3))))
    w, et, ex = g.spring_arm(p, i), g.cap_ear_t(p), p.cap_ear_x
    ew = g.ear_w(p, i)
    ears = at_springs(lambda: Part.makeBox(et, ew, w - ro + 4, V(-et, -ew / 2, ro - 4)).fuse(
        Part.makeCylinder(et / 2, ew, V(-ex, ew / 2, w), V(0, -1, 0))))
    body = fuse([cyl_x(ro, -h, 0)] + lobes + ears)
    tools = [socket_cavity(i, p), ellip_cone_mx(h + 2, g.beta_y(p, i), g.beta_p(p, i)), roll_slot(i, p, -h - 1, 0.01)]
    tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, t + 2, V(-t - 1, 0, pcd), X))
    tools += at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 40, V(-ex, 20, w), V(0, -1, 0)))
    return cut(body, tools)


def fin_windows(i, p):
    bl, rf = g.body_len(p, i), g.RF(p, i)
    x_f0 = 0.0
    xm = x_f0 + 0.5 * (bl - x_f0)
    out = []
    for s0, s1 in ((x_f0 + 7, xm - 2), (xm + 2 * p.line_w + 10, bl - g.flange_t(p) - 3)):
        r_in = (g.cap_outer_r(p, i) if s0 < g.seat_depth(p, i) + 3 else spine_r(i, p)) + 4
        r_out = rf - 7
        h = min((s1 - s0) / 2 - 1, (r_out - r_in) / 2)
        if h <= 5:
            continue
        nr = max(1, int((r_out - r_in + 3) // (2 * h + 3)))
        for k in range(nr):
            b = Part.makeBox(h * math.sqrt(2), 20, h * math.sqrt(2), V(-h / math.sqrt(2), -10, -h / math.sqrt(2)))
            b.rotate(V(0, 0, 0), Y, 45)
            b.translate(V((s0 + s1) / 2, 0, r_in + h + k * (2 * h + 3)))
            out.append(b)
    return out


def spine_r(i, p):
    if i < p.joint_count:
        return max(g.flange_bolt_r(p, i + 1) - 5.3, g.bore_r(p) + g.wall(p))
    return g.bore_r(p) + g.wall(p, 4)


def createFrame(i, p):
    bl, sd, rf, ho = g.body_len(p, i), g.seat_depth(p, i), g.RF(p, i), g.cap_outer_r(p, i)
    pcd, lr, n = g.bolt_pcd_r(p, i), g.lobe_r(p), p.joint_count
    fin_t = g.fin_t(p, i)
    x_f0 = 0.0
    rr = g.flange_r(p, i + 1) if i < n else spine_r(i, p) + 6
    parts = [cyl_x(ho, 0, sd), cyl_x(spine_r(i, p), sd - 2, bl), cyl_x(rr, bl - g.flange_t(p), bl)]
    # cap-bolt lobes with 45 deg undersides
    drop = pcd + lr - ho + 3
    parts += at_lobes(lambda: Part.makeCylinder(lr, 7, V(0, 0, pcd), X).fuse(
        Part.makeLoft([Part.Wire(Part.makeCircle(lr, V(7, 0, pcd), X)), Part.Wire(Part.makeCircle(1, V(7 + drop, 0, ho - 3), X))], True)))
    for a in (0, 90, 180, 270):
        parts.append(rot_x(Part.makeBox(bl - x_f0, fin_t, rf, V(x_f0, -fin_t / 2, 0)), a))
    xm = x_f0 + 0.5 * (bl - x_f0)
    t = 2 * p.line_w + 0.2
    ring = cyl_x(rf, xm, xm + t).cut(cyl_x(rf - 3 * p.line_w, xm - 1, xm + t + 1))
    skirt = cone_x(rf, rf - 8, xm + t, xm + t + 8).cut(cone_x(rf - 3 * p.line_w, rf - 8 - 3 * p.line_w, xm + t - 0.01, xm + t + 8.01))
    base = cyl_x(rf, bl - g.flange_t(p), bl).cut(cyl_x(rf - 3 * p.line_w, bl - g.flange_t(p) - 1, bl + 1))
    if i < n:
        w2 = g.spring_arm(p, i + 1)
        ft = g.fin_t(p, i)
        parts += at_springs(lambda: Part.makeCylinder(7, ft + 4, V(bl - 4, (ft + 4) / 2, w2), V(0, -1, 0)).common(
            Part.makeBox(20, 40, 400, V(bl - 20, -20, 0))))
    body = fuse(parts + [ring, skirt, base])
    tools = [socket_cavity(i, p), roll_slot(i, p, -0.01, sd), cyl_x(g.bore_r(p), -1, bl + 1)]
    for a in (0, 90, 180, 270):
        tools += [rot_x(w, a) for w in fin_windows(i, p)]
    tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, 12, V(-1, 0, pcd), X).fuse(hex_prism_x(p.nut_af, 7 - p.nut_h - 0.3, 20, pcd)))
    if i < n:
        w2 = g.spring_arm(p, i + 1)
        tools += at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 20, V(bl - 4, 10, w2), V(0, -1, 0)))
        fb = g.flange_bolt_r(p, i + 1)
        tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, g.flange_t(p) + 2, V(bl - g.flange_t(p) - 1, 0, fb), X).fuse(
            hex_prism_x(p.nut_af, bl - g.flange_t(p) + 2.5 - 20, 20, fb)))
    else:
        tools += at_lobes(lambda: Part.makeCylinder(1.6, g.flange_t(p) + 2, V(bl - g.flange_t(p) - 1, 0, spine_r(i, p) + 2), X))
    return cut(body, tools)


def createTipAdapter(p):
    n = p.joint_count
    r = spine_r(n, p) + 6
    L = g.tip_plug_len(p)
    body = fuse([cyl_x(r, 0, 6), cyl_x(10.5, 0, L), cone_x(7, 2, L, L + 45)] +
                [cone_x(8 - 1.2 * k, 5 - 1.2 * k, L + 8 + 9 * k, L + 13 + 9 * k) for k in range(4)])
    tools = [cyl_x(g.bore_r(p), -1, 80), cyl_x(7, 6, L + 2)]
    tools += at_lobes(lambda: Part.makeCylinder(1.6, 8, V(-1, 0, spine_r(n, p) + 2), X))
    return cut(body, tools)


def root_placement(p):
    th = math.radians(p.root_pitch)
    ex, ez = V(-math.cos(th), 0, -math.sin(th)), V(-math.sin(th), 0, math.cos(th))
    ey = ez.cross(ex)
    m = App.Matrix(ex.x, ey.x, ez.x, -p.root_back_offset,
                   ex.y, ey.y, ez.y, 0,
                   ex.z, ey.z, ez.z, 0,
                   0, 0, 0, 1)
    return App.Placement(m)


def createHipMount(p):
    """Harness plate + boss + spring anchor arms, built in the pelvis frame."""
    P = root_placement(p)
    df, ft = g.DF(p, 1), g.flange_t(p)
    pf = df + ft
    w = g.spring_arm(p, 1)
    fin_t = 3 * p.line_w + 0.1
    plate = Part.makeBox(p.hip_plate_t, p.hip_plate_w, p.hip_plate_h,
                         V(-p.harness_plate_offset - p.hip_plate_t, -p.hip_plate_w / 2, -p.hip_plate_h / 2))
    # boss: a cylinder on the tail axis from the ball-1 flange forward through the plate
    reach = (p.root_back_offset - p.harness_plate_offset) / math.cos(math.radians(p.root_pitch)) + 20
    local = [cyl_x(g.flange_r(p, 1) + 4, -reach, -pf)]
    for a in (0, 90, -90):
        arm = Part.makeBox(12, fin_t + 2, w + 5, V(-pf - 12, -fin_t / 2 - 1, 0))
        web = Part.makeBox(reach - pf - 12, fin_t + 2, 0.5 * w, V(-reach, -fin_t / 2 - 1, 0))
        local += [rot_x(arm, a), rot_x(web, a)]
    tail_side = Part.makeBox(100, 200, 200, V(-pf + 0.01, -100, -100))
    local_tools = [tail_side, cyl_x(g.bore_r(p), -pf - 80, 0), cyl_x(9, -pf - 36, -pf - 22),
                   Part.makeBox(14, 18, 60, V(-pf - 36, -9, -60))]
    local_tools += at_lobes(lambda: Part.makeCylinder(p.bolt_clear / 2, 12, V(-pf - 11, 0, g.flange_bolt_r(p, 1)), X).fuse(
        hex_prism_x(p.nut_af, -pf - 26, 20, g.flange_bolt_r(p, 1))))
    local_tools += at_springs(lambda: Part.makeCylinder(p.spring_hole / 2, 20, V(-g.spring_span_parent(p, 1), 10, w), V(0, -1, 0)))

    def place(s):
        return s.transformGeometry(P.toMatrix())

    tail_part = place(fuse(local))
    # keep only what lies behind the harness plate's front face
    keep = Part.makeBox(400, 400, 400, V(-p.harness_plate_offset - 400, -200, -200))
    body = fuse([plate, tail_part.common(keep)])
    tools = [place(s) for s in local_tools]
    for y in (-75, 75):
        for zz in (-50, 50):
            tools.append(Part.makeCylinder(3.3, p.hip_plate_t + 2, V(-p.harness_plate_offset + 1, y - 5, zz), V(-1, 0, 0)).fuse(
                Part.makeCylinder(3.3, p.hip_plate_t + 2, V(-p.harness_plate_offset + 1, y + 5, zz), V(-1, 0, 0))).fuse(
                Part.makeBox(p.hip_plate_t + 2, 10, 6.6, V(-p.harness_plate_offset - p.hip_plate_t - 1, y - 5, zz - 3.3))))
    for y in (-60, 60):
        tools.append(Part.makeBox(p.hip_plate_t + 2, 52, 4, V(-p.harness_plate_offset - p.hip_plate_t - 1, y - 26, -p.hip_plate_h / 2 + 8)))
    return cut(body, tools)


# ------------------------------------------------------------------ document


def add(doc, group, name, shape, placement, color):
    o = doc.addObject("Part::Feature", name)
    o.Shape = shape
    o.Placement = placement
    if hasattr(o, "ViewObject") and o.ViewObject is not None:
        o.ViewObject.ShapeColor = color
    group.addObject(o)
    return o


def createVertebra(index, parameters, doc, parent, placement):
    """Vertebra `index` = its socket (seat is part of the frame, plus the bolted
    cap), its frame, and the ball of the next joint bolted to its distal flange."""
    p = parameters
    grp = doc.addObject("App::DocumentObjectGroup", f"Vertebra{index:02d}")
    parent.addObject(grp)
    add(doc, grp, f"Vertebra{index:02d}_Frame", createFrame(index, p), placement, (0.26, 0.45, 0.70))
    add(doc, grp, f"Vertebra{index:02d}_Socket", createCap(index, p), placement, (0.70, 0.78, 0.90))
    L = g.spacing(p)
    if index < p.joint_count:
        add(doc, grp, f"Vertebra{index:02d}_Ball", createBall(index + 1, p),
            placement.multiply(App.Placement(V(L, 0, 0), App.Rotation())), (0.85, 0.65, 0.13))
    else:
        add(doc, grp, f"Vertebra{index:02d}_TipAdapter", createTipAdapter(p),
            placement.multiply(App.Placement(V(g.body_len(p, index), 0, 0), App.Rotation())), (0.85, 0.65, 0.13))
    return grp


def build(p, joints=None, name="SuitTail"):
    doc = App.newDocument(name)
    top = doc.addObject("App::DocumentObjectGroup", name)
    sheet = doc.addObject("Spreadsheet::Sheet", "Parameters")
    for k, (key, val) in enumerate(json.loads(p.to_json()).items()):
        sheet.set(f"A{k+1}", key)
        sheet.set(f"B{k+1}", str(val) if isinstance(val, list) else f"{val}")
    hip = doc.addObject("App::DocumentObjectGroup", "HipMount")
    top.addObject(hip)
    add(doc, hip, "HipMount_Plate", createHipMount(p), App.Placement(), (0.3, 0.3, 0.3))
    P = root_placement(p)
    add(doc, hip, "HipMount_Ball", createBall(1, p), P, (0.85, 0.65, 0.13))
    L = g.spacing(p)
    joints = joints or p.joint_count
    pts = [P.multVec(V(-g.DF(p, 1) - 20, 0, 0))]
    pl = P
    for i in range(1, joints + 1):
        if i > 1:
            pl = pl.multiply(App.Placement(V(L, 0, 0), App.Rotation(Y, p.rest_droop)))
        createVertebra(i, p, doc, top, pl)
        pts.append(pl.Base)
    end = pl.multVec(V(L, 0, 0))
    pts.append(end)
    cord = doc.addObject("Part::Feature", "CentralCord")
    cord.Shape = Part.makePolygon(pts)
    top.addObject(cord)
    if joints == p.joint_count:
        tip = doc.addObject("Part::Feature", "FoamTipReference")
        tl = p.tail_length - p.mech_length
        tip.Shape = cone_x(p.last_mech_diameter / 2, p.tip_diameter / 2, 0, tl)
        tip.Placement = pl.multiply(App.Placement(V(L, 0, 0), App.Rotation()))
        top.addObject(tip)
    doc.recompute()
    return doc


def main():
    p = g.CadParams()
    report = {"checks_failed": [c for c in g.checks(p) if not c[1]]}
    doc = build(p)
    shapes = [o for o in doc.Objects if o.TypeId == "Part::Feature" and o.Name != "CentralCord"]
    for o in shapes:
        report.setdefault("valid", {})[o.Name] = bool(o.Shape.isValid())
        report.setdefault("volume_cm3", {})[o.Name] = round(o.Shape.Volume / 1000, 2)
    Part.export(shapes, str(OUT / "suit_tail.step"))
    doc.saveAs(str(OUT / "suit_tail.FCStd"))
    App.closeDocument(doc.Name)
    doc4 = build(p, joints=4, name="TestSection4")
    Part.export([o for o in doc4.Objects if o.TypeId == "Part::Feature" and o.Name != "CentralCord"], str(OUT / "test_section_4joint.step"))
    doc4.saveAs(str(OUT / "test_section_4joint.FCStd"))
    (OUT / "build_report.json").write_text(json.dumps(report, indent=1))
    print("BUILD_OK", sum(report["valid"].values()), "/", len(report["valid"]), "valid solids")


try:
    main()
except Exception:
    traceback.print_exc()
    (OUT / "build_report.json").write_text(json.dumps({"error": traceback.format_exc()}))
    raise
