"""Write the Gojira CAD variant (from the simulated design) as JSON + OpenSCAD parameters.

    PYTHONPATH=. ~/.venvs/costumebipedaltail/bin/python cad/make_variant.py
"""
import json
from dataclasses import asdict
from pathlib import Path

from cad import geometry as g

ROOT = Path(__file__).resolve().parent


def gojira_params():
    import sys
    sys.argv = sys.argv[:1]
    from experiments.gojira_compare import gojira
    return gojira().cad()


def write(name, c):
    (ROOT / "variants").mkdir(exist_ok=True)
    (ROOT / "variants" / f"{name}.json").write_text(json.dumps(asdict(c), indent=1))
    lines = [f"// generated by cad/make_variant.py from the simulated '{name}' design - do not edit",
             'include <suit_tail.scad>']
    keys = ["joint_count", "tail_length", "mech_length", "root_diameter", "last_mech_diameter", "tip_diameter",
            "taper_exponent", "skin_root", "skin_tip", "cord_preload", "pitch_ratio", "max_roll", "root_pitch"]
    for k in keys:
        lines.append(f"{k} = {getattr(c, k)};")
    lines.append(f"max_yaw = {[round(x, 4) for x in c.max_yaw]};")
    lines.append("max_pitch = [for (y = max_yaw) y * pitch_ratio];")
    lines.append(f"rest_droop_list = {[round(x, 4) for x in c.rest_droop_list]};")
    (ROOT / "openscad" / f"suit_tail_{name}.scad").write_text("\n".join(lines) + "\n")
    return c


if __name__ == "__main__":
    c = write("gojira", gojira_params())
    print("joints", c.joint_count, "root pitch", round(c.root_pitch, 2), "droops", [round(x, 2) for x in c.rest_droop_list])
    bad = [x for x in g.checks(c) if not x[1]]
    print("checks failed:", bad)
